#!/usr/bin/env node
// Writes projects/{portal,display}/src/environments/environment.ts from env vars.
// Local dev uses your hand-edited environment.ts (gitignored); Vercel uses this script
// to materialise the file at build time from project-level env vars.
//
// Required env: SUPABASE_URL, SUPABASE_ANON_KEY
// Optional env: NODE_ENV (defaults to 'development' for local, set to 'production' in Vercel)
//
// Idempotency: if SUPABASE_URL is unset (typical local dev), the script no-ops so it
// doesn't clobber the developer's local file. Vercel always sets the env vars.

import { writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const url = process.env.SUPABASE_URL;
const anon = process.env.SUPABASE_ANON_KEY;

if (!url || !anon) {
  // Local dev path: trust the existing files. Bail with a hint if they're missing.
  const portalExists = existsSync(resolve(repoRoot, 'projects/portal/src/environments/environment.ts'));
  const displayExists = existsSync(resolve(repoRoot, 'projects/display/src/environments/environment.ts'));
  if (!portalExists || !displayExists) {
    console.error(
      '[generate-env] Missing environment.ts file(s) and SUPABASE_URL/SUPABASE_ANON_KEY are not set.\n' +
      '  Local dev: copy environment.example.ts to environment.ts in each app and fill in values.\n' +
      '  CI/Vercel: set SUPABASE_URL and SUPABASE_ANON_KEY as project env vars.'
    );
    process.exit(1);
  }
  console.log('[generate-env] SUPABASE_URL not set — leaving existing environment.ts files in place.');
  process.exit(0);
}

const production = process.env.NODE_ENV === 'production' || process.env.VERCEL === '1';

const contents = `// AUTO-GENERATED by scripts/generate-env.mjs. Do not edit by hand on Vercel.
// Local dev: this file is gitignored; edit it directly or run scripts/generate-env.mjs.
export const environment = {
  production: ${production},
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(anon)},
};
`;

for (const app of ['portal', 'display']) {
  const target = resolve(repoRoot, `projects/${app}/src/environments/environment.ts`);
  writeFileSync(target, contents);
  console.log(`[generate-env] wrote ${target}`);
}
